#!/pro/bin/perl

use strict;
use warnings;

my @perls = (
#   "perl5.005_04",	# Not supported by Devel::Cover
    "perl5.6.2",	# 5.6.2  threaded 64bitint
    "perl5.8.8",	# 5.8.8  64bitint defined-or
    "perl5.10.0",	# 5.10.0 64bitint debug
    "/usr/bin/perl",	# 5.12.1 thread
    "perl",		# 5.12.2 64bitint longdouble
    );

-f "Makefile" and qx{make -i distclean};
qx{rm -rf cover_db sandbox/cover_db*};

my $n = 0;
foreach my $p (@perls) {
    print STDERR "Running cover for $p ...\n";
    unlink "cover_db";
    qx{$p Makefile.PL};
    qx{ccache -C};
    unlink glob "*.gc*";
    qx{make};
    qx{$p /pro/bin/cover -test};

    system "mv cover_db sandbox/cover_db_".++$n;
    $p eq "perl" or qx{make distclean 2>/dev/null};
    }

# The last should be first
system qq{cover -nogcov sandbox/cover_db_?};
system "cpdir sandbox/cover_db_$n sandbox/cover_db_0";
system qq{cover -nogcov sandbox/cover_db_?};
