#!/bin/sh

make distclean

# 5.6.2 threaded 64bitint nodebug
perl5.6.2 Makefile.PL
ccache -C
rm -f *.gc*
cover -test

mv cover_db cover_db_
make distclean

# 5.10.0 64bitint debug
perl Makefile.PL
mv cover_db_ cover_db
ccache -C
rm -f *.gc*
cover -test --nodelete
